### ISSUE TITLE
option for snippet

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-fragment-field#4]
i assume you switch logic based on name of field, its page objects template or whatever combination. I will use this plugin for quiet a few different cases and using an option to trigger a snippet directly would be awesome. just like [snippetfield](https://github.com/jenstornell/kirby-snippetfield) does.

```yaml
fields:
  my_logic_field:
    title: My logic field
    type: logic
    snippet: logic/awesome
```

i will probably build my own plugin based on yours, just wanting to let you know about the idea.
