### ISSUE TITLE
You example blueprint should have label, not text

### ISSUE THREAD

**Issue by texnixe** [jenstornell/kirby-fragment-field#5]
```
fields:
  my_logic_field:
    title: My logic field
    type: logic
```

Instead:

```
fields:
  my_logic_field:
    label: My logic field
    type: logic
```
